services:
  api01: &api01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgresql://admin:rinhanest123@postgres:5432/new-rinha?schema=public&connection_limit=15
      PORT: 3333
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '120MB'

  api02:
    <<: *api01
    ports:
      - '3334:3333'
    environment:
      DATABASE_URL: postgresql://admin:rinhanest123@postgres:5432/new-rinha?schema=public&connection_limit=15
      PORT: 3333

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '50MB'
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - PGUSER=admin
      - POSTGRES_PASSWORD=rinhanest123
      - POSTGRES_DB=rinha
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '210MB'
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge